### ISSUE TITLE
get_version_name is not found

### ISSUE THREAD

**Issue by songxiaoliang** [TGPSKI/androidBuildVariants#1]
get_version_name / get_version_name  is not found

log: 

[12:34:37]: fastlane finished with errors

[!] Could not find action, lane or variable 'get_version_name'. Check out the documentation for more details: https://docs.fastlane.tools/actions

**Comment by TGPSKI** [comment]
You have to install the plugins as part of the fastlane setup process.

Plugins:
https://github.com/TGPSKI/androidBuildTypes/blob/master/fastlane/Pluginfile

get_version_name repo:
https://github.com/Jems22/fastlane-plugin-get-version-name
